-- Supabase (Postgres) schema for Student Management System

create table if not exists batches (
  batch_id bigint generated by default as identity primary key,
  batch_name text not null unique,
  created_by text not null,
  created_at timestamptz not null default now()
);

create table if not exists students (
  student_id bigint generated by default as identity primary key,
  batch_id bigint not null references batches(batch_id) on delete cascade,
  student_id_roll text not null,
  first_name text not null,
  last_name text not null,
  course text,
  department text,
  year text,
  section text,
  email text,
  phone text,
  hostel_status text default 'day-scholar',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists students_unique_roll
  on students (batch_id, department, lower(student_id_roll));

create table if not exists year_records (
  year_record_id bigint generated by default as identity primary key,
  student_id bigint not null references students(student_id) on delete cascade,
  batch_id bigint not null references batches(batch_id) on delete cascade,
  year integer not null,
  tuition_fee numeric default 0,
  books_fee numeric default 0,
  bus_fee numeric default 0,
  hostel_fee numeric default 0,
  misc_fee numeric default 0,
  total_fee numeric default 0,
  paid_amount numeric default 0,
  outstanding_amount numeric default 0,
  status text default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, year)
);

create table if not exists payments (
  payment_id bigint generated by default as identity primary key,
  year_record_id bigint not null references year_records(year_record_id) on delete cascade,
  student_id bigint not null references students(student_id) on delete cascade,
  batch_id bigint not null references batches(batch_id) on delete cascade,
  bill_number text not null,
  receipt_number text not null,
  amount numeric not null,
  payment_method text,
  payment_date date not null,
  reference_number text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists payments_unique_bill
  on payments (batch_id, lower(bill_number));

create unique index if not exists payments_unique_receipt
  on payments (receipt_number);

create table if not exists audit_logs (
  log_id bigint generated by default as identity primary key,
  batch_id bigint not null references batches(batch_id) on delete cascade,
  action text not null,
  entity_type text not null,
  entity_id bigint,
  details text,
  timestamp timestamptz not null default now()
);

create table if not exists attendance_records (
  attendance_id bigint generated by default as identity primary key,
  batch_id bigint not null references batches(batch_id) on delete cascade,
  student_id bigint not null references students(student_id) on delete cascade,
  date date not null,
  present boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (batch_id, student_id, date)
);

create table if not exists attendance_settings (
  batch_id bigint not null references batches(batch_id) on delete cascade,
  month text not null,
  exclude_weekends boolean not null default true,
  holidays text[] not null default array[]::text[],
  updated_at timestamptz not null default now(),
  primary key (batch_id, month)
);

create or replace function next_receipt_number(batch_id_input bigint)
returns text
language plpgsql
as $$
declare
  next_number integer;
begin
  select coalesce(max((regexp_replace(receipt_number, '^RCPT-', ''))::integer), 0) + 1
    into next_number
    from payments
    where batch_id = batch_id_input;

  return 'RCPT-' || lpad(next_number::text, 5, '0');
end;
$$;

create or replace function reset_sequences()
returns void
language plpgsql
as $$
begin
  perform setval(pg_get_serial_sequence('batches', 'batch_id'), coalesce((select max(batch_id) from batches), 0));
  perform setval(pg_get_serial_sequence('students', 'student_id'), coalesce((select max(student_id) from students), 0));
  perform setval(pg_get_serial_sequence('year_records', 'year_record_id'), coalesce((select max(year_record_id) from year_records), 0));
  perform setval(pg_get_serial_sequence('payments', 'payment_id'), coalesce((select max(payment_id) from payments), 0));
  perform setval(pg_get_serial_sequence('audit_logs', 'log_id'), coalesce((select max(log_id) from audit_logs), 0));
  perform setval(pg_get_serial_sequence('attendance_records', 'attendance_id'), coalesce((select max(attendance_id) from attendance_records), 0));
end;
$$;
